percona/k8spxc-docs

docs/helm.md
Namespaces are just confusing.
=> K8SPXC-1107 - Update helm.md

docs/kubernetes.md
"by your own" should probably be "on your own"
=> Minor grammar update

docs/compare.md
* remove links to MongoDB operators
* PS operator does not support PITR
=> K8SPXC-1186 fix misprints

docs/users.md
* clustercheck user is marked as deprecated
* add correct description for monitor user
=> K8SPXC-1170 update description for users

_resource/overrides/main.html, mkdocs-base.yml, requirements.txt
modified:   _resource/overrides/main.html
modified:   mkdocs-base.yml
modified:   requirements.txt
=> Add text snippets to link previews

docs/copyright.md, docs/trademark-policy.md, mkdocs-base.yml
new file:   docs/copyright.md
new file:   docs/trademark-policy.md
modified:   mkdocs-base.yml
=> DOCS-72 Update Trademark Policy, Copyright and Licensing Information (k8spxc)

docs/haproxy-conf.md, docs/proxysql-conf.md
=> K8SPXC-1183 mention PXC Pods restart at ProxySQL -> HAProxy switch

docs/backups-restore.md
The instructions for restoring from backup used an example from MongoDB
=> Doc: Restore backup: Config has been fixed

docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.0.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.1.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.10.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.11.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.12.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.13.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.2.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.3.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.4.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.5.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.6.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.7.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.8.0.md, docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.9.0.md, docs/System-Requirements.md, docs/backups-move-from-external-db.md, docs/custom-registry.md, mkdocs-base.yml
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.0.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.1.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.10.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.11.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.12.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.13.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.2.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.3.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.4.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.5.0.md
modified:   docs/ReleaseNotes/Kubernetes-Operator-for-PXC-RN1.6.0.md
modified: …
=> CLOUD-795 Removed TOC from welcome page

docs/proxysql-conf.md
=> Fixed typo in work Secret

docs/assets/fragments/connectivity.txt, docs/kubernetes.md, docs/minikube.md, docs/openshift.md, mkdocs-base.yml
modified:   docs/assets/fragments/connectivity.txt
modified:   docs/kubernetes.md
modified:   docs/minikube.md
modified:   docs/openshift.md
modified:   mkdocs-base.yml
=> CLOUD-681 Fixed connectivity.txt and added it to install instructions

_resource/overrides/main.html
=> K8SPXC-1386 Add PostHog script and configure dashboards for PXC operators

_resource/overrides/partials/header.html, docs/js/percona-select.js, docs/versions.json, mkdocs-base.yml, versions.json
modified:   _resource/overrides/partials/header.html
new file:   docs/js/percona-select.js
modified:   mkdocs-base.yml
=> Fix the version selector

docs/backups-ondemand.md
=> K8SPXC-1547 Added a command to track a backup progress

docs/assets/fragments/patch-update-db.txt, docs/patch-update-db.md, docs/update-automatic.md, docs/update-db.md, docs/update-minor-set-version.md, docs/update-operator.md, docs/update.md, docs/update_manually.md, mkdocs-base.yml, snippets/update-assumptions.md
Restructured the docs, created topic-based pages
Created a top-level nav item
=>  K8SPXC-1471 Updated the upgrade doc

docs/operator.md
=> K8SPXC-1599 Documented loadBalancerClass option

docs/dr-restore.md, docs/operator.md
=> K8SPXC-1472 Added a deprecation warning to loadBalancerIP field

docs/options.md
modified:   docs/dr-restore.md
modified:   docs/operator.md
=> K8SPXC-1347 Removed restriction to not modify require-secure-transport

docs/annotations.md, docs/css/design.css, mkdocs-base.yml
Added a diagram
Adjusted css to render it correctly in dark mode
=> K8SPXC-1569 Documented labels and annotations

docs/backups-scheduled.md, docs/operator.md
modified:   docs/backups-scheduled.md
modified:   docs/operator.md
=> K8SPXC-1375 Documented a new retention subsection for scheduled backups

docs/containers-conf.md
Updated the page to improve the wording, structure and flow
=> K8SPXC-1284 Documented how to define TCP protocol for  peer-list SRV lookup

docs/openshift.md, docs/update_openshift.md
modified:   docs/openshift.md
modified:   docs/update_openshift.md
=> Updated OpenShift install and update docs to address issues with OS 4.19

docs/update-operator.md
=> K8SPXC-1714 Fixed image path for backups
